<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>4ff74198-59da-4860-b183-e0722e56da32</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>
		<DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Data\Extensions\**" />
		<Content Remove="Data\Extensions\**" />
		<EmbeddedResource Remove="Data\Extensions\**" />
		<None Remove="Data\Extensions\**" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\discount.proto" GrpcServices="Server" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.1-preview.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\building-blocks\BuildingBlocks\BuildingBlocks.csproj" />
	</ItemGroup>

</Project>
