services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__catalog-postgres-db=Host=catalog-postgres-db;Port=5432;Database=catalog-postgres-db;Username=postgres;Password=postgres
    ports:
      - "6000:8080"
      - "6060:8081"
    depends_on:
      - catalog-postgres-db
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  catalog-postgres-db:
    container_name: catalog-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog-postgres-db
    restart: always
    ports:
      - 5433:5432
    volumes:
      - catalog-postgres:/var/lib/postgresql
      
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Host=basket-postgres-db;Port=5432;Database=basket-postgres-db;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=basket-redis-cache:6379
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  basket-postgres-db:
    container_name: basket-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=basket-postgres-db
    restart: always
    ports:
      - 5434:5432
    volumes:
      - basket-postgres:/var/lib/postgresql
  basket-redis-cache:
    container_name: basket-redis-cache
    restart: always
    ports:
      - 6381:6379

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discountdb
      # - ConnectionStrings__Database=Data Source=/db/discountdb.db
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      # - discount-sqlite:/db
