services:
  # -------------------------
  # DATABASES & CACHES
  # -------------------------
  catalog-postgres-db: 
    image: postgres:latest
    networks:
      - catalog-network 

  basket-postgres-db: 
    image: postgres:latest
    networks:
      - basket-network 

  basket-redis-cache: 
    image: redis:latest
    networks:
      - basket-network 

  ordering-sql-server-db: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - ordering-network

  # -------------------------
  # APIs
  # -------------------------
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: ./services/catalog/Catalog.API/Dockerfile
    depends_on:
      - catalog-postgres-db
    networks:
      - catalog-network 
      - eshop-network

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/basket/Basket.API/Dockerfile
    depends_on:
      - basket-postgres-db
      - basket-redis-cache
      - discount.grpc
    networks:
      - basket-network 
      - eshop-network

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: services/discount/Discount.Grpc/Dockerfile
    networks:
      - eshop-network      
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: services/ordering/Ordering.API/Dockerfile
    depends_on:
      - ordering-sql-server-db
    networks:
      - ordering-network 
      - eshop-network
# -------------------------
# VOLUMES & NETWORKS
# -------------------------

volumes:
  catalog-postgres:  
  basket-postgres:  
  # discount-sqlite:  
  ordering-sql-server-db:

networks:
  eshop-network:
    driver: bridge
  catalog-network:
    driver: bridge
  basket-network:
    driver: bridge
  ordering-network:
    driver: bridge
