services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: ./services/catalog/Catalog.API/Dockerfile
    networks:
      - catalog-network 
  catalog-postgres-db: 
    image: postgres:latest
    networks:
      - catalog-network 
      - eshop-network


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/basket/Basket.API/Dockerfile
    networks:
      - basket-network 
      - eshop-network
  basket-postgres-db: 
    image: postgres:latest
    networks:
      - basket-network 
  basket-redis-cache: 
    image: redis:latest
    networks:
      - basket-network 

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: services/discount/Discount.Grpc/Dockerfile
    networks:
      - eshop-networkfeat: add gRPC communication between Basket and Discount services

volumes:
  catalog-postgres:  
  basket-postgres:  
  # discount-sqlite:  

networks:
  eshop-network:
    driver: bridge
  catalog-network:
    driver: bridge
  basket-network:
    driver: bridge

